# Generated by Django 2.1.2 on 2020-02-02 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200202_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultymember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='password',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='username',
        ),
        migrations.AddField(
            model_name='facultymember',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
